framework:
  messenger:
    failure_transport: failed

    transports:
      # Transport pour les échecs
      failed: 'doctrine://default?queue_name=failed'

      # Transport synchrone (pour les emails)
      sync: 'sync://'

      # Transport asynchrone (pour les autres messages)
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          use_notify: true
          check_delayed_interval: 60000
        retry_strategy:
          max_retries: 3
          multiplier: 2

    routing:
      # Envoi IMMÉDIAT des emails
      Symfony\Component\Mailer\Messenger\SendEmailMessage: sync

      # Envoi asynchrone pour les autres types de messages
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async

      # Exemple pour vos propres messages
      # 'App\Message\YourMessage': async

    buses:
      messenger.bus.default:
        # Middleware optionnels
        middleware:
          - doctrine_ping_connection
          - doctrine_close_connection