# config/packages/security.yaml
security:
    # Configure password hashers to automatically choose the best available algorithm
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User provider configuration to use the database entity for authentication
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email  # We authenticate by email (can be changed to another field)

    # Firewalls to manage authentication and security for different parts of the application
    firewalls:
        # Dev firewall to disable security for development-related paths (e.g., profiler, assets)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main firewall for normal routes (including login)
        main:
            # Enable lazy loading for this firewall
            lazy: true
            # Use the user provider for this firewall
            provider: app_user_provider

            # Configuring form login (used for username/password authentication)
            form_login:
                login_path: app_login      # The route for login form (from LoginController)
                check_path: app_login      # The path to submit the login form to
                default_target_path: app_home  # The default route to redirect to after successful login
                username_parameter: _username  # Field for username (email in this case)
                password_parameter: _password  # Field for password
                # If necessary, you can configure the authenticator here

            # Configuring logout
            logout:
                path: app_logout          # Path for logging out
                target: app_login          # Where to redirect after logout

    # Access control rules to specify which roles have access to which paths
    access_control:
        # Only users with ROLE_USER or higher can access the home page
        - { path: ^/home, roles: ROLE_USER }
        # Example for admin path access control
        # - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            # For testing, reduce the work factor to the lowest possible values
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
