parameters:
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Configuration principale
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Configuration spécifique pour les contrôleurs
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    
    App\Service\NotificationService:
        arguments:
            $requestStack: '@request_stack'