parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\CustomAuthenticationSuccessHandler:
        arguments:
            $router: '@router'
            $security: '@security.helper'

    App\Service\CountryService: ~

    App\Form\RegistrationFormType:
        arguments:
            $countryService: '@App\Service\CountryService'
